variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  environment:
    name: prod
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  tags:
    - gitlab-org-docker
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n ${CI_REGISTRY_USER}:${CI_REGISTRY_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_TAG --destination $IMAGE_LATEST
  only:
    refs:
      - main

deploy:
  stage: deploy
  image: gmschurchdev/kubectl:alpine-latest
  environment:
    name: prod
    kubernetes:
      namespace: production
  tags:
    - gitlab-org-docker
  script:
    - kubectl set image deployment/logic-test logic-test=$IMAGE_TAG
  only:
    refs:
      - main
